// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLUfMpMysjgxsCOnwmxI3TVtB9p2LITM',
    appId: '1:436357693563:android:f75109485dca39bb2da2de',
    messagingSenderId: '436357693563',
    projectId: 'totalx1',
    storageBucket: 'totalx1.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCsvV4fM5DHHGwQ6eQ2CGtDaDtvuuFRE',
    appId: '1:436357693563:web:279e3c62dd408fc42da2de',
    messagingSenderId: '436357693563',
    projectId: 'totalx1',
    authDomain: 'totalx1.firebaseapp.com',
    storageBucket: 'totalx1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABIl5HqDfin7yz7yi7nb60rxaBpgyx048',
    appId: '1:436357693563:ios:b4dfad28497524d32da2de',
    messagingSenderId: '436357693563',
    projectId: 'totalx1',
    storageBucket: 'totalx1.appspot.com',
    iosBundleId: 'com.example.totalxMachineTest',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIl5HqDfin7yz7yi7nb60rxaBpgyx048',
    appId: '1:436357693563:ios:b4dfad28497524d32da2de',
    messagingSenderId: '436357693563',
    projectId: 'totalx1',
    storageBucket: 'totalx1.appspot.com',
    iosBundleId: 'com.example.totalxMachineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhCsvV4fM5DHHGwQ6eQ2CGtDaDtvuuFRE',
    appId: '1:436357693563:web:482f9d1f0200597a2da2de',
    messagingSenderId: '436357693563',
    projectId: 'totalx1',
    authDomain: 'totalx1.firebaseapp.com',
    storageBucket: 'totalx1.appspot.com',
  );

}